# Generated by Django 4.2.7 on 2023-11-11 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 11, 12, 0, 11, 32, 249774))),
            ],
        ),
    ]
